name: Publish BOM and Properties to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Publish to GitHub Packages
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload izgw-versions.properties as artifact
        uses: actions/upload-artifact@v4
        with:
          name: izgw-versions.properties
          path: izgw-versions.properties

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: izgw-versions.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
