name: Publish BOM and Properties to GitHub Packages

on:
  push:
    branches:
      - Release*
      - main
      - develop

  pull_request:
    branches:
      - Release*
      - main
      - develop
      
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Publish to GitHub Packages
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload izgw-versions.properties as artifact
        uses: actions/upload-artifact@v4
        with:
          name: izgw-versions.properties
          path: izgw-versions.properties

      - name: Create tag from build number
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag v1.${{ github.run_number }}
          git push origin v1.${{ github.run_number }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.${{ github.run_number }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}